name: check

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
    - uses: actions/checkout@v2
    - name: update apt
      if: contains(matrix.os, 'ubuntu')
      run: sudo apt update
    - name: install deps
      if: contains(matrix.os, 'ubuntu')
      run: sudo apt-get install libasound2-dev libudev-dev
    - name: install web target
      run: rustup target add wasm32-unknown-unknown
    - name: test
      run: cargo test --verbose --all-features
    - name: test web
      run: cargo test --verbose --all-features --no-run --target wasm32-unknown-unknown

